In [2]:
import numpy as np

## 5.5 활성화 함수 계층 구현하기

### 5.5.1 ReLU 계층

In [3]:
# common/layers.py
class Relu:
    def __init__(self):
        self.mask = None

    def forward(self, x):
        self.mask = (x <= 0) # x가 0 이하인 위치를 True로 기록
        out = x.copy() # 입력값을 복사
        out[self.mask] = 0 # mask가 True인 곳(즉, 0 이하인 값)을 0으로 변경

        return out # 수정된 출력을 반환

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout

        return dx

In [6]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])
x   #array 출력

array([[ 1. , -0.5],
       [-2. ,  3. ]])

In [8]:
relu = Relu()   #Relu 통과, 인스턴스 생성
y = relu.forward(x) #순전파
y

array([[1., 0.],
       [0., 3.]])

In [9]:
relu.mask

array([[False,  True],
       [ True, False]])

In [10]:
relu.backward(np.ones((2,2)))

array([[1., 0.],
       [0., 1.]])

## 5.5.2 Sigmoid 계층


In [11]:
# common/layers.py
class Sigmoid:
    def __init__(self):
        self.out = None

    def forward(self, x):
        def sigmoid(x):
            return 1 / (1 + np.exp(-x))    
        out = sigmoid(x)
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out #(1-y)*y

        return dx

In [12]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])
x

array([[ 1. , -0.5],
       [-2. ,  3. ]])

In [13]:
sigmoid = Sigmoid()
y = sigmoid.forward(x)
y

array([[0.73105858, 0.37754067],
       [0.11920292, 0.95257413]])

In [14]:
sigmoid.backward(1)

array([[0.19661193, 0.23500371],
       [0.10499359, 0.04517666]])